// 'use strict';
//
// var json = {
//   "koa": "^2.0.0-alpha.7",
//   "lodash": "^4.13.1",
//   "pino": "^2.12.1",
//
//
//   "browser-sync": "^2.11.0",
//   "chalk": "^1.1.1",
//   "del": "^2.0.1",
//   "gulp": "github:gulpjs/gulp#4.0",
//   "gulp-angular-filesort": "github:xinshangshangxin/gulp-angular-filesort",
//   "gulp-angular-templatecache": "^2.0.0",
//   "gulp-cached": "^1.1.0",
//   "gulp-concat": "^2.2.0",
//   "gulp-cssnano": "^2.0.0",
//   "gulp-filter": "^4.0.0",
//   "gulp-htmlmin": "^2.0.0",
//   "gulp-if": "^2.0.0",
//   "gulp-inject": "^4.0.0",
//   "gulp-jshint": "^2.0.0",
//   "gulp-less": "^3.0.3",
//   "gulp-load-plugins": "^1.1.0",
//   "gulp-ng-annotate": "^2.0.0",
//   "gulp-remember": "^0.3.1",
//   "gulp-rename": "^1.2.2",
//   "gulp-replace": "^0.5.4",
//   "gulp-rev": "^7.0.0",
//   "gulp-uglify": "^2.0.0",
//   "jshint": "^2.9.1",
//   "jshint-stylish": "^2.0.1",
//   "log-symbols": "^1.0.2",
//   "node-notifier": "^4.6.1",
//   "streamqueue": "^1.1.1",
//   "supertest": "^2.0.0",
//   "through2": "^2.0.0",
//
//
//   "angular": "~1.5.8",
//   "angular-animate": "1.4.4",
//   "angular-bootstrap": "0.14.3",
//   "angular-loading-bar": "0.9.0",
//   "angular-resource": "1.4.4",
//   "angular-translate": "2.4.2",
//   "angular-translate-loader-static-files": "2.4.2",
//   "angular-ui-router": "0.2.15",
//   "bootstrap": "3.3.6",
//   "font-awesome": "4.6.3",
//   "lodash": "4.13.1"
// }